param(
  [Parameter(Mandatory = $false)]
  [string] $InputPath = "menu-identificadores/menu-identificadores.json",

  [Parameter(Mandatory = $false)]
  [ValidateSet("json", "csv", "ts")]
  [string] $Format = "json",

  [Parameter(Mandatory = $false)]
  [string] $OutputPath = "",

  [Parameter(Mandatory = $false)]
  [switch] $OnlyMenu
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-AttrValue {
  param(
    [Parameter(Mandatory = $true)] $Attrs,
    [Parameter(Mandatory = $true)] [string] $Name
  )
  if ($null -eq $Attrs) { return $null }
  $prop = $Attrs.PSObject.Properties[$Name]
  if ($null -eq $prop) { return $null }
  return $prop.Value
}

function Normalize-Key {
  param([Parameter(Mandatory = $true)][string] $Key)
  $k = $Key.Trim()
  $k = $k -replace "[^A-Za-z0-9]+", "_"
  $k = $k -replace "_{2,}", "_"
  $k = $k.Trim("_")
  if ([string]::IsNullOrWhiteSpace($k)) { $k = "ref" }
  if ($k -match "^[0-9]") { $k = "k_" + $k }
  return $k
}

if (-not (Test-Path $InputPath)) {
  throw "InputPath not found: $InputPath"
}

$raw = Get-Content $InputPath -Raw
$data = $raw | ConvertFrom-Json

$rows = foreach ($item in $data) {
  $attrs = $item.attrs

  $id = Get-AttrValue -Attrs $attrs -Name "id"
  $dataModuloFuncao = Get-AttrValue -Attrs $attrs -Name "data-modulo-funcao"
  $dataModulo = Get-AttrValue -Attrs $attrs -Name "data-modulo"
  $dataFuncao = Get-AttrValue -Attrs $attrs -Name "data-funcao"
  $dataHref = Get-AttrValue -Attrs $attrs -Name "data-href"
  $dataTipoFuncao = Get-AttrValue -Attrs $attrs -Name "data-tipo-funcao"
  $dataTipoLink = Get-AttrValue -Attrs $attrs -Name "data-tipo-link"
  $href = Get-AttrValue -Attrs $attrs -Name "href"
  $cls = Get-AttrValue -Attrs $attrs -Name "class"
  $onclick = Get-AttrValue -Attrs $attrs -Name "onclick"

  if ($OnlyMenu) {
    $isAnchor = ($item.tag -eq "a")
    $looksMenu =
      ($dataTipoLink -in @("link", "menu")) -or
      (($cls -is [string]) -and ($cls -match "(^|\\s)item-menu(\\s|$)"))
    if (-not ($isAnchor -and $looksMenu)) { continue }
  }

  $preferredKey =
    $(if (-not [string]::IsNullOrWhiteSpace($dataModuloFuncao)) { $dataModuloFuncao }
      elseif (-not [string]::IsNullOrWhiteSpace($id)) { $id }
      elseif (-not [string]::IsNullOrWhiteSpace($item.locatorSuggested)) { $item.locatorSuggested }
      else { "$($item.tag):$($item.text)" })

  [pscustomobject]@{
    index             = $item.index
    key               = (Normalize-Key $preferredKey)
    keySource         = $preferredKey
    text              = $item.text
    tag               = $item.tag
    frameUrl          = $item.frameUrl
    visible           = $item.visible
    locatorSuggested  = $item.locatorSuggested

    id                = $id
    class             = $cls
    href              = $href
    onclick           = $onclick

    data_modulo_funcao = $dataModuloFuncao
    data_modulo        = $dataModulo
    data_funcao        = $dataFuncao
    data_href          = $dataHref
    data_tipo_funcao   = $dataTipoFuncao
    data_tipo_link     = $dataTipoLink
  }
}

# Dedupe keys for TS export; keep first occurrence and suffix collisions.
$seen = @{}
$deduped = foreach ($r in $rows) {
  $k = $r.key
  if (-not $seen.ContainsKey($k)) {
    $seen[$k] = 1
    $r
    continue
  }
  $seen[$k]++
  $r.key = "${k}_$($seen[$k])"
  $r
}

function Write-OutputText {
  param([Parameter(Mandatory = $true)][string] $Text)
  if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    Write-Output $Text
  } else {
    $dir = Split-Path -Parent $OutputPath
    if (-not [string]::IsNullOrWhiteSpace($dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Set-Content -Path $OutputPath -Value $Text -Encoding UTF8
    Write-Output "Wrote: $OutputPath"
  }
}

switch ($Format) {
  "json" {
    $json = $deduped | ConvertTo-Json -Depth 6
    Write-OutputText -Text $json
  }
  "csv" {
    if ([string]::IsNullOrWhiteSpace($OutputPath)) {
      $deduped | ConvertTo-Csv -NoTypeInformation | Write-Output
    } else {
      $dir = Split-Path -Parent $OutputPath
      if (-not [string]::IsNullOrWhiteSpace($dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
      $deduped | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
      Write-Output "Wrote: $OutputPath"
    }
  }
  "ts" {
    $pairs = foreach ($r in $deduped) {
      if ([string]::IsNullOrWhiteSpace($r.locatorSuggested)) { continue }
      [pscustomobject]@{ key = $r.key; locator = $r.locatorSuggested }
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("/* Auto-generated by skills/menu-references/scripts/extract-menu-references.ps1 */")
    $lines.Add("export const menuLocators = {")
    foreach ($p in $pairs) {
      # TS single-quoted string literal escaping (value remains unchanged at runtime).
      $k = $p.key.Replace("\\", "\\\\").Replace("'", "\'")
      $v = $p.locator.Replace("\\", "\\\\").Replace("'", "\'")
      $lines.Add("  '$k': '$v',")
    }
    $lines.Add("} as const;")
    $lines.Add("")
    $lines.Add("export type MenuLocatorKey = keyof typeof menuLocators;")

    Write-OutputText -Text ($lines -join "`n")
  }
  default {
    throw "Unknown Format: $Format"
  }
}
